In [9]:
import json
import pandas as pd
import numpy as np

from sqlalchemy import create_engine
import psycopg2

from config import db_password

import time

In [14]:
#read csv file
file_path = "POSTGRES/UseMe_2020NFL3rdLong_Clean99.csv"
Clean_df = pd.read_csv(file_path)
Clean_df

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,Yards,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2020122602,12/26/2020,2,9,44,LV,MIA,2,10,-9,...,0,0,NaN,18,OPP,0,NaN,0,NaN,0
1,2020122602,12/26/2020,2,9,3,LV,MIA,3,19,18,...,0,0,LEFT GUARD,27,OPP,0,NaN,0,NaN,0
2,2020122500,12/25/2020,3,1,17,MIN,NO,3,9,0,...,0,0,NaN,33,OPP,0,NO,1,DEFENSIVE HOLDING,0
3,2020122500,12/25/2020,3,1,12,MIN,NO,1,10,0,...,0,0,NaN,18,OPP,1,NO,1,DEFENSIVE PASS INTERFERENCE,17
4,2020122500,12/25/2020,3,1,6,MIN,NO,1,1,-3,...,0,0,LEFT GUARD,1,OPP,0,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46184,2020091300,9/13/2020,4,1,38,ATL,SEA,2,9,2,...,0,0,NaN,20,OPP,0,NaN,0,NaN,0
46185,2020091300,9/13/2020,4,5,18,NaN,NaN,0,0,0,...,0,0,NaN,0,OPP,0,NaN,0,NaN,0
46186,2020091300,9/13/2020,4,2,0,ATL,SEA,1,10,1,...,0,0,NaN,21,OPP,0,NaN,0,NaN,0
46187,2020091300,9/13/2020,4,2,0,NaN,NaN,0,0,0,...,0,0,NaN,0,OPP,0,NaN,0,NaN,0
46188,2020091300,9/13/2020,4,2,16,ATL,SEA,1,10,12,...,0,0,NaN,33,OPP,0,NaN,0,NaN,0

In [11]:
import os

In [15]:
df = pd.read_sql('test_data', 'postgres:///db_name')

         GameId    GameDate
0    2020111900  2020-11-19
1    2020121305  2020-12-13
2    2020092010  2020-09-20
3    2020101804  2020-10-18
4    2021010309  2021-01-03
..          ...         ...
250  2020121307  2020-12-13
251  2020092400  2020-09-24
252  2020102500  2020-10-25
253  2020101101  2020-10-11
254  2020092100  2020-09-21

[255 rows x 2 columns]

In [16]:
db_string = f"postgres://postgres:{db_password}@127.0.0.1:5432/movie_data"
    engine = create_engine(db_string)
    movies_df.to_sql(name='movies', con=engine, if_exists='replace')

KeyError: "None of [Index(['GameId', 'GameDate'], dtype='object')] are in the [columns]"

In [ ]:
Play99_df = Play99_df.loc[:, ["PlayId",
    "GameId", "Quarter", "Minute", "Second", "OffenseTeam", "DefenseTeam", "Down", "ToGo", "Yards",
    "YardsPlusMinus", "Successful3rdDown", "YardLine", "SeriesFirstDown", "NextScore", "Description", "TeamWin", "SeasonYear",
    "Formation", "PlayType", "IsRush", "IsPass", "IsIncomplete", "IsTouchdown", "PassType", "IsSack", "IsChallenge",
    "IsChallengeReversed", "IsMeasurement", "IsInterception", "IsFumble", "IsPenalty", "IsTwoPointConversion", "IsTwoPointConversionSuccessful",
    "RushDirection", "YardLineFixed", "YardLineDirection", "IsPenaltyAccepted", "PenaltyTeam", "IsNoPlay", "PenaltyType",
    "PenaltyYards",
                   ]]

In [ ]:
db_string = f"postgres://postgres:{db_password}@127.0.0.1:5432/project_data"

In [ ]:
engine = create_engine(db_string)

In [ ]:
table name
Game99_df.to_sql(name='Game99', con=engine)

In [ ]:
#Table name
Play99_df.to_sql(name='Play99', con=engine)

In [ ]:
#create config.py to store pgadmin password

In [ ]:
#run code, go to pg admin, check to see if tables are present, type querie select * from (table name) both tables**